/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplication.*;

/**
 *
 * @author alumnogreibd
 */
public class VPagos extends javax.swing.JDialog {
    private VPrincipal padre;
    private FachadaAplicacion fa;

    /**
     * Creates new form VPagos
     */
    public VPagos(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        this.fa = fa;    
        this.avisoResultado.setVisible(false);
        this.avisoVehiculoNoAparcado.setVisible(false);
        this.avisoVehiculoNoSeleccionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        buscarMat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarFechaMin = new javax.swing.JTextField();
        buscarFechaMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscarCosteMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscarCosteMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buscarAp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buscarDurMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buscarDurMax = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAparcar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        buscarPlaza = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReservar = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        buscarDni = new javax.swing.JTextField();
        avisoResultado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRetirarVehiculo = new javax.swing.JButton();
        avisoVehiculoNoSeleccionado = new javax.swing.JLabel();
        avisoVehiculoNoAparcado = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Matrícula");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        buscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMatActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha Mínima");

        jLabel3.setText("Fecha Máxima");

        buscarFechaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFechaMinActionPerformed(evt);
            }
        });

        buscarFechaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFechaMaxActionPerformed(evt);
            }
        });

        jLabel4.setText("Coste Mínimo");

        buscarCosteMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCosteMinActionPerformed(evt);
            }
        });

        jLabel5.setText("Coste Máximo");

        jLabel6.setText("Aparcamiento");

        buscarAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarApActionPerformed(evt);
            }
        });

        jLabel7.setText("Duración Mínima");

        jLabel8.setText("Duración Máxima");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaAparcar.setModel(new ModeloTablaAparcar());
        tablaAparcar.setShowGrid(true);
        jScrollPane2.setViewportView(tablaAparcar);

        jLabel9.setText("Plaza");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel10.setText("Estacionamientos");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel11.setText("Reservas");

        tablaReservar.setModel(new ModeloTablaReservar());
        tablaReservar.setShowGrid(true);
        jScrollPane3.setViewportView(tablaReservar);

        jLabel12.setText("DNI");

        avisoResultado.setForeground(new java.awt.Color(255, 0, 0));
        avisoResultado.setText("No se encontraron resultados");

        jLabel13.setBackground(new java.awt.Color(153, 153, 255));
        jLabel13.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("?");
        jLabel13.setToolTipText("Deben incluirse los cinco caracteres del la id del Aparcamiento. Ejemplo: 00000");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(153, 153, 255));
        jLabel14.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("?");
        jLabel14.setToolTipText("Los decimales deben introducirse con punto, no coma");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(153, 153, 255));
        jLabel15.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("?");
        jLabel15.setToolTipText("Los decimales deben introducirse con punto, no coma");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(153, 153, 255));
        jLabel16.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("?");
        jLabel16.setToolTipText("Formato: 0d 0h 0m 0s");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(153, 153, 255));
        jLabel18.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("?");
        jLabel18.setToolTipText("Formato: aaaa-mm-dd");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("?");
        jLabel19.setToolTipText("Formato: aaaa-mm-dd");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);

        btnRetirarVehiculo.setText("Retirar Vehículo");
        btnRetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarVehiculoActionPerformed(evt);
            }
        });

        avisoVehiculoNoSeleccionado.setForeground(new java.awt.Color(255, 0, 0));
        avisoVehiculoNoSeleccionado.setText("No se ha seleccionado ningún vehículo");

        avisoVehiculoNoAparcado.setForeground(new java.awt.Color(255, 0, 0));
        avisoVehiculoNoAparcado.setText("Este vehiculo no se encuentra aparcado");

        jLabel20.setBackground(new java.awt.Color(153, 153, 255));
        jLabel20.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("?");
        jLabel20.setToolTipText("Formato: 0d 0h 0m 0s. Ejemplos: 1d | 1d 1m | 10h | 1d 1m 1h 1s");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarAp, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarCosteMin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarCosteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarFechaMin)
                            .addComponent(buscarDurMin, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarDurMax, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(buscarFechaMax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avisoResultado)
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avisoVehiculoNoAparcado)
                        .addGap(18, 18, 18)
                        .addComponent(avisoVehiculoNoSeleccionado)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetirarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(buscarPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(buscarCosteMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buscarCosteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(buscarDurMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(buscarDurMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarFechaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscarFechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avisoResultado)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnRetirarVehiculo)
                    .addComponent(avisoVehiculoNoSeleccionado)
                    .addComponent(avisoVehiculoNoAparcado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.getAccessibleContext().setAccessibleDescription("Formato: 0d 0h 0m 0s. Ejemplos: 1d | 1d 1m | 10h | 1d 1m 1h 1s");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se ejecuta al presionar el boton 'Volver' de la ventana. Cierra la ventana de pagos.
     * @param evt - Evento
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void buscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMatActionPerformed

    private void buscarFechaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFechaMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFechaMinActionPerformed

    private void buscarCosteMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCosteMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCosteMinActionPerformed

    private void buscarFechaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFechaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFechaMaxActionPerformed

    private void buscarApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarApActionPerformed

    /**
     * Este metodo se ejecuta al presionar el boton 'Buscar' de la ventana. Llama al metodo que realizara la busqueda de todas las tuplas
     * de aparcamientos y reservas deseadas.
     * Si es asi, da acceso a la aplicacion. Si no, muestra un mensaje de error.
     * @param evt - Evento
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarPagos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarVehiculoActionPerformed
        retirarVehiculo();
    }//GEN-LAST:event_btnRetirarVehiculoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoResultado;
    private javax.swing.JLabel avisoVehiculoNoAparcado;
    private javax.swing.JLabel avisoVehiculoNoSeleccionado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRetirarVehiculo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField buscarAp;
    private javax.swing.JTextField buscarCosteMax;
    private javax.swing.JTextField buscarCosteMin;
    private javax.swing.JTextField buscarDni;
    private javax.swing.JTextField buscarDurMax;
    private javax.swing.JTextField buscarDurMin;
    private javax.swing.JTextField buscarFechaMax;
    private javax.swing.JTextField buscarFechaMin;
    private javax.swing.JTextField buscarMat;
    private javax.swing.JTextField buscarPlaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaAparcar;
    private javax.swing.JTable tablaReservar;
    // End of variables declaration//GEN-END:variables

    /**
     * Este metodo es llamado por btnBuscarActionPerformed, que se ejecuta al presionar el boton 'Aceptar' de la ventana.
     * Toma todos los parametros introducidos en los campos de busqueda y recupera las tuplas de las tablas
     * 'Aparcar' y 'Reservar' que cumplan las condiciones. Para ello, se sirve de dos funciones de la fachada de la aplicacion.
     * Tambien inicializa las JTable en las que se van a mostrar los datos, y las rellena.
     */
    public void buscarPagos () {
        this.avisoResultado.setVisible(false);
        this.avisoVehiculoNoAparcado.setVisible(false);
        this.avisoVehiculoNoSeleccionado.setVisible(false);
        
        ModeloTablaAparcar ta;
        ModeloTablaReservar tr;
        
        ta = (ModeloTablaAparcar) tablaAparcar.getModel();
        tr = (ModeloTablaReservar) tablaReservar.getModel();
        ta.setFilas(fa.historialAparcar(buscarDni.getText(), buscarMat.getText(), buscarPlaza.getText(), buscarAp.getText(), buscarCosteMax.getText(), buscarCosteMin.getText(), buscarDurMax.getText(), buscarDurMin.getText(), buscarFechaMax.getText(), buscarFechaMin.getText()));
        tr.setFilas(fa.historialReservar(buscarDni.getText(), buscarMat.getText(), buscarPlaza.getText(), buscarAp.getText(), buscarCosteMax.getText(), buscarCosteMin.getText(), buscarDurMax.getText(), buscarDurMin.getText(), buscarFechaMax.getText(), buscarFechaMin.getText()));
    
        if(ta.getRowCount() == 0 && tr.getRowCount() == 0) {
            this.avisoResultado.setVisible(true);
        }
    }
    
    /**
     * Este metodo se ejecuta al pulsar el boton 'Retirar Vehiculo'. Actualiza en la base de datos la tupla, asignandole al campo 'fechasalida' el momento actual.
     */
    public void retirarVehiculo () {
        this.avisoResultado.setVisible(false);
        this.avisoVehiculoNoAparcado.setVisible(false);
        this.avisoVehiculoNoSeleccionado.setVisible(false);
        
        int fila = tablaAparcar.getSelectedRow();
        if (fila == -1) {
            avisoVehiculoNoSeleccionado.setVisible(true);
            return;
        }
        if (tablaAparcar.getValueAt(fila, 5) != null) {
            avisoVehiculoNoAparcado.setVisible(true);
            return;
        }
        fa.retirarVehiculo(tablaAparcar.getValueAt(fila, 1).toString(),
                tablaAparcar.getValueAt(fila, 2).toString(),
                tablaAparcar.getValueAt(fila, 3).toString(),
                tablaAparcar.getValueAt(fila, 4).toString());
        
        buscarPagos();
    }
}
