/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;


/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    aplication.FachadaAplicacion fa;
    
    /** Creates new form VPrincipal */
    public VPrincipal(aplication.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionPagos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        ButtonReservar = new javax.swing.JButton();
        addPlaza = new javax.swing.JButton();
        elimPlaza = new javax.swing.JButton();
        addUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aparcamientos USC");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        btnGestionPagos.setText("Historial de Pagos");
        btnGestionPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPagosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        ButtonReservar.setText("Reservar/Aparcar");
        ButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReservarActionPerformed(evt);
            }
        });

        addPlaza.setText("Anadir Plaza");
        addPlaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlazaActionPerformed(evt);
            }
        });

        elimPlaza.setText("Eliminar Plaza");
        elimPlaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimPlazaActionPerformed(evt);
            }
        });

        addUsuario.setText("Añadir usuario");
        addUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsuarioActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnGestionPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addPlaza)
                        .addComponent(elimPlaza)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(addPlaza)
                .addGap(18, 18, 18)
                .addComponent(elimPlaza)
                .addGap(67, 67, 67)
                .addComponent(addUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGestionPagos)
                    .addComponent(ButtonReservar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPagosActionPerformed
        fa.historialPagos();
    }//GEN-LAST:event_btnGestionPagosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit (0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReservarActionPerformed
        VAviso aviso;
        if(fa.getUsuario().getNumeroInfracciones()>=5){
            aviso=new VAviso(this,true, "Tienes demasiadas infracciones como para reservar o aparcar.");
            aviso.setVisible(true);
            return;
        }
        VReservarAparcar vreservar=new VReservarAparcar(this,true, fa);
        vreservar.setVisible(true);
    }//GEN-LAST:event_ButtonReservarActionPerformed

    private void addPlazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlazaActionPerformed
        
        VAnadir vanadir=new VAnadir(this,true, fa);
        vanadir.setVisible(true);
         
    }//GEN-LAST:event_addPlazaActionPerformed

    private void elimPlazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimPlazaActionPerformed
        
        VEliminar veliminar=new VEliminar(this,true, fa);
        veliminar.setVisible(true);
  
    }//GEN-LAST:event_elimPlazaActionPerformed
    private void addUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsuarioActionPerformed
        VNuevoUsuario vNuevoUsuario=new VNuevoUsuario(this,true, fa);
        vNuevoUsuario.setVisible(true);
    }//GEN-LAST:event_addUsuarioActionPerformed
    
    /**
    * @param args the command line argumentss
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReservar;
    private javax.swing.JButton addPlaza;
    private javax.swing.JButton addUsuario;
    private javax.swing.JButton btnGestionPagos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton elimPlaza;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
