/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplication.Usuario;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alumnogreibd
 */
public class VRegistroInfracciones extends javax.swing.JFrame {
    
    aplication.FachadaAplicacion fa;
    String dni;
    Usuario  usuario;
    
    /**
     * Creates new form RegistroInfracciones
     */
    public VRegistroInfracciones(aplication.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        this.textoAviso.setVisible(false);
        this.avisoVeto.setVisible(false);
        this.avisoVeto2.setVisible(false);
        this.btnConfirmar.setEnabled(false);
        this.dni=null;
        usuario= null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        dniLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        matriculaField = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        textoAviso = new javax.swing.JLabel();
        avisoVeto = new javax.swing.JLabel();
        avisoVeto2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaActividad = new javax.swing.JList<>();
        volverBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.gray);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jTextPane1.setText("REGISTRO DE INFRACCIONES");
        jScrollPane1.setViewportView(jTextPane1);

        dniLabel.setText("MATRICULA:");

        jLabel1.setText("Escribe a continuación la MATRICULA del coche de la persona a la cual se le quiera añadir la infracción:");

        matriculaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaFieldActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar Registro Infraccion");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        tablaUsuario.setModel(new ModeloTablaUsuarios());
        tablaUsuario.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(tablaUsuario);

        textoAviso.setForeground(new java.awt.Color(255, 51, 51));
        textoAviso.setText("No se ha encontrado el usuario del vehiculo");

        avisoVeto.setForeground(new java.awt.Color(255, 0, 0));
        avisoVeto.setText("SE HA REGISTRADO UN VETO");

        avisoVeto2.setForeground(new java.awt.Color(255, 0, 0));
        avisoVeto2.setText("ESTE USUARIO YA TIENE REGISTRADO UN VETO");

        listaActividad.setModel(new ModeloListaStrings());
        listaActividad.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ModeloListaStrings listactividad;
        listactividad = (ModeloListaStrings) this.listaActividad.getModel();
        for(int i = 0; i< this.fa.getUsuariosSalvados().size();i++){
            String texto = "Se ha quitado el veto de "+this.fa.getUsuariosSalvados().get(i)+", ya que han pasado más de 14 días desde el veto";
            listactividad.nuevoElemento(texto);
        }
        listaActividad.setName(""); // NOI18N
        jScrollPane2.setViewportView(listaActividad);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 3, 13)); // NOI18N
        jLabel2.setText("Actividad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(matriculaField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoAviso)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(volverBtn))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(avisoVeto2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(btnConfirmar)
                        .addGap(59, 59, 59)
                        .addComponent(avisoVeto)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(textoAviso))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(avisoVeto2)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avisoVeto)
                            .addComponent(btnConfirmar))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volverBtn)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaFieldActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /*Vaciar tabla*/ 
        ModeloTablaUsuarios m;
        m=(ModeloTablaUsuarios) tablaUsuario.getModel();
        ArrayList<Usuario> lista = new ArrayList<>();
        m.setFilas(lista);
        
        
        this.avisoVeto.setVisible(false);
        this.avisoVeto2.setVisible(false);
        usuario = buscarUsuario(matriculaField.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        registrarInfraccion(this.dni);
        this.usuario = fa.obtenerUsuario(this.matriculaField.getText());
        
        this.btnConfirmar.setEnabled(false); //é ddecir solo se pode pulsar unha vez, porque se deshabilita ao pulsalo
        if(usuario.getFechaVeto()==null){
            anhadirListaActividad(1);
        }
        else{
            anhadirListaActividad(2);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroInfracciones().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoVeto;
    private javax.swing.JLabel avisoVeto2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> listaActividad;
    private javax.swing.JTextField matriculaField;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JLabel textoAviso;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     * @param dni 
     * busca un Usuario polo seu dni [dni] e mostrao nunha linea
     */
    public Usuario buscarUsuario(String matricula){
        ModeloTablaUsuarios m;
        
        m=(ModeloTablaUsuarios) tablaUsuario.getModel();
        ArrayList<Usuario> lista = new ArrayList<>();
        Usuario usuario = fa.obtenerUsuario(matricula);
        if(usuario==null){
            this.textoAviso.setVisible(true);
        }
        else{
            this.btnConfirmar.setEnabled(true);
            lista.add(usuario);
            m.setFilas(lista);
            if (m.getRowCount() > 0) {
                tablaUsuario.setRowSelectionInterval(0, 0);
                this.textoAviso.setVisible(false);
            }
            this.dni = usuario.getDni();
            if (usuario.getFechaVeto()!=null) {
                this.btnConfirmar.setEnabled(false);
                this.avisoVeto2.setVisible(true);
            }
            return usuario;
        }
        return null;
    }
    
    public void registrarInfraccion(String dni){
        if(dni != null){
            if(fa.registrarInfraccion(dni)==5){
                this.avisoVeto.setVisible(true);
                this.btnConfirmar.setEnabled(false);
            }
        }
    }
    /**
     * Esta funcion deberia anhadir na lista os registros de infracciones exitosos asi como que se registra veto
     * si i=1, entonces sale que se ejecutou correctamente o registro
     * si i=2, entonces sale que se registrou un veto
     */
    public void anhadirListaActividad(int i){
        ModeloListaStrings listact;
        listact = (ModeloListaStrings) this.listaActividad.getModel();
         String textoMeter1 = "Registrado con exito infracción en DNI "+this.dni+" que tiene un TOTAL de "+fa.mostrarNumeroInfracciones(this.dni)+" infracciones.";
         String textoMeter2 = "Alcanzado numero maximo de infracciones, registrado veto en DNI "+this.dni;
         if(i==1){
             listact.nuevoElemento(textoMeter1);
         }else if(i==2){
             listact.nuevoElemento(textoMeter2);
         }
         this.listaActividad.setSelectedIndex(listact.getSize()-1);
    }


}
