/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplication.FachadaAplicacion;

/**
 *
 * @author alumnogreibd
 */
public class VReservarAparcar extends javax.swing.JDialog {

    /**
     * Creates new form VReservar
     */
    private FachadaAplicacion fa;

    public VReservarAparcar(java.awt.Frame parent, boolean modal,  FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAparcamiento = new java.awt.Label();
        aparcamientoINPUT = new javax.swing.JTextField();
        txtCodigoPlaza = new java.awt.Label();
        codigoPlazaINPUT = new javax.swing.JTextField();
        txtAparcamiento1 = new java.awt.Label();
        tipoPlazaINPUT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservar = new javax.swing.JTable();
        ButtonBuscar = new javax.swing.JButton();
        reservarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAparcar = new javax.swing.JTable();
        AvisoSeleccionaPlaza1 = new java.awt.Label();
        AvisoSeleccionaPlaza2 = new java.awt.Label();
        jButtonAparcar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAparcamiento.setText("Aparcamiento:");

        txtCodigoPlaza.setText("Codigo Plaza:");

        codigoPlazaINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPlazaINPUTActionPerformed(evt);
            }
        });

        txtAparcamiento1.setText("Tipo Plaza");

        tipoPlazaINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPlazaINPUTActionPerformed(evt);
            }
        });

        jTableReservar.setModel(new gui.ModeloTablaPlazaReserva());
        jScrollPane1.setViewportView(jTableReservar);

        ButtonBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        reservarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        reservarButton.setText("Reservar");
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableAparcar.setModel(new gui.ModeloTablaPlazaAparcar());
        jScrollPane2.setViewportView(jTableAparcar);

        AvisoSeleccionaPlaza1.setForeground(new java.awt.Color(255, 51, 51));

        AvisoSeleccionaPlaza2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvisoSeleccionaPlaza2.setForeground(new java.awt.Color(255, 51, 51));

        jButtonAparcar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonAparcar.setText("Aparcar");
        jButtonAparcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAparcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtAparcamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aparcamientoINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(txtCodigoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codigoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(281, 281, 281)
                                        .addComponent(reservarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AvisoSeleccionaPlaza2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtAparcamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jButtonAparcar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvisoSeleccionaPlaza1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aparcamientoINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAparcamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAparcamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservarButton)
                    .addComponent(AvisoSeleccionaPlaza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAparcar)
                    .addComponent(AvisoSeleccionaPlaza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoPlazaINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPlazaINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPlazaINPUTActionPerformed

    private void tipoPlazaINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPlazaINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPlazaINPUTActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
         ModeloTablaPlazaReserva m;
         ModeloTablaPlazaAparcar mA;

        m=(ModeloTablaPlazaReserva) jTableReservar.getModel();
        mA=(ModeloTablaPlazaAparcar) jTableAparcar.getModel();
        //Control de errores
        String str = codigoPlazaINPUT.getText();
        int num;
        if (str.isEmpty()) {
            num = -1; // o cualquier otro valor predeterminado
        } else {
            try{num = Integer.parseInt(str);}catch(Exception e){ //convertir codidoPlaza a tipo int
                 AvisoSeleccionaPlaza2.setText("El codigo de la plaza debe ser un numero");
                return;
            }
            
        }
        AvisoSeleccionaPlaza2.setText("");
        //Actualizar Tabla con todas las plazas Reserva
        m.setFilas(fa.obtenerPlazasReserva(aparcamientoINPUT.getText(),num,tipoPlazaINPUT.getText(), false));
        if (m.getRowCount() > 0) {
            jTableReservar.setRowSelectionInterval(0, 0);
        }
                //Actualizar Tabla con todas las plazas Aparcar
        mA.setFilas(fa.obtenerPlazasAparcar(aparcamientoINPUT.getText(),num,tipoPlazaINPUT.getText(), false));
        if (m.getRowCount() > 0) {
            jTableAparcar.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
       // VAviso aviso;
        VHacerReserva vselec;//nueva ventana que se va a crear
        int fila=jTableReservar.getSelectedRow();
        if(fila==-1){
            //aviso=new VAviso(this,true, "No has seleccionado ninguna plaza");
            //aviso.setVisible(true);
            AvisoSeleccionaPlaza2.setText("No has seleccionado ninguna plaza");
            return;
        }
            AvisoSeleccionaPlaza2.setText("");

        String ap= jTableReservar.getValueAt(fila, 0).toString();
        int plaza= Integer.parseInt(jTableReservar.getValueAt (fila, 1).toString());
        String tipo= jTableReservar.getValueAt(fila, 2).toString();

        vselec=new VHacerReserva(this,true, fa, ap, plaza, tipo); //se le pasan los datos de la plaza seleccionada
        vselec.setVisible(true);
    }//GEN-LAST:event_reservarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.fa.getFbd().getDaoUsuarios().commitTransaction();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAparcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAparcarActionPerformed
    VAparcar vselec;
        int fila=jTableAparcar.getSelectedRow();
        if(fila==-1){
            //aviso=new VAviso(this,true, "No has seleccionado ninguna plaza");
            //aviso.setVisible(true);
            AvisoSeleccionaPlaza1.setText("No has seleccionado ninguna plaza");
            return;
        }
            AvisoSeleccionaPlaza1.setText("");

        String ap= jTableAparcar.getValueAt(fila, 0).toString();
        int plaza= Integer.parseInt(jTableAparcar.getValueAt (fila, 1).toString());
        String tipo= jTableAparcar.getValueAt(fila, 2).toString();

        vselec=new VAparcar(this,true, fa, ap, plaza, tipo);
        vselec.setVisible(true);    }//GEN-LAST:event_jButtonAparcarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label AvisoSeleccionaPlaza1;
    private java.awt.Label AvisoSeleccionaPlaza2;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JTextField aparcamientoINPUT;
    private javax.swing.JTextField codigoPlazaINPUT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAparcar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAparcar;
    private javax.swing.JTable jTableReservar;
    private javax.swing.JButton reservarButton;
    private javax.swing.JTextField tipoPlazaINPUT;
    private java.awt.Label txtAparcamiento;
    private java.awt.Label txtAparcamiento1;
    private java.awt.Label txtCodigoPlaza;
    // End of variables declaration//GEN-END:variables
}
