/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplication.FachadaAplicacion;

/**
 *
 * @author alumnogreibd
 */
public class VReservarAparcar extends javax.swing.JDialog {

    /**
     * Creates new form VReservar
     */
    private FachadaAplicacion fa;

    public VReservarAparcar(java.awt.Frame parent, boolean modal,  FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAparcamiento = new java.awt.Label();
        aparcamientoINPUT = new javax.swing.JTextField();
        txtCodigoPlaza = new java.awt.Label();
        codigoPlazaINPUT = new javax.swing.JTextField();
        txtAparcamiento1 = new java.awt.Label();
        tipoPlazaINPUT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlazasReserva = new javax.swing.JTable();
        ButtonBuscar = new javax.swing.JButton();
        reservarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAparcamiento.setText("Aparcamiento:");

        txtCodigoPlaza.setText("Codigo Plaza:");

        codigoPlazaINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPlazaINPUTActionPerformed(evt);
            }
        });

        txtAparcamiento1.setText("Tipo Plaza");

        tipoPlazaINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPlazaINPUTActionPerformed(evt);
            }
        });

        tablaPlazasReserva.setModel(new gui.ModeloTablaPlaza());
        jScrollPane1.setViewportView(tablaPlazasReserva);

        ButtonBuscar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        reservarButton.setText("Reservar");
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reservarButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAparcamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aparcamientoINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtCodigoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(txtAparcamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aparcamientoINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAparcamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAparcamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoPlazaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(reservarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoPlazaINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPlazaINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPlazaINPUTActionPerformed

    private void tipoPlazaINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPlazaINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPlazaINPUTActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
         ModeloTablaPlaza m;

        m=(ModeloTablaPlaza) tablaPlazasReserva.getModel();
        
        //Control de errores
        String str = codigoPlazaINPUT.getText();
        int num;
        if (str.isEmpty()) {
            num = -1; // o cualquier otro valor predeterminado
        } else {
            num = Integer.parseInt(str);
        }
        m.setFilas(fa.obtenerPlazasReserva(aparcamientoINPUT.getText(),num,tipoPlazaINPUT.getText(), false));
        if (m.getRowCount() > 0) {
            tablaPlazasReserva.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
        VAviso aviso;
        VSeleccionarVehiculo vselec;
        int fila=tablaPlazasReserva.getSelectedRow();
        if(fila==-1){
            aviso=new VAviso(this,true, "No has seleccionado ninguna plaza");
            aviso.setVisible(true);
            return;
        }

        String ap= tablaPlazasReserva.getValueAt(fila, 0).toString();
        int plaza= Integer.parseInt(tablaPlazasReserva.getValueAt (fila, 1).toString());
        String tipo= tablaPlazasReserva.getValueAt(fila, 2).toString();

        vselec=new VSeleccionarVehiculo(this,true, fa, ap, plaza, tipo);
        vselec.setVisible(true);
    }//GEN-LAST:event_reservarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JTextField aparcamientoINPUT;
    private javax.swing.JTextField codigoPlazaINPUT;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reservarButton;
    private javax.swing.JTable tablaPlazasReserva;
    private javax.swing.JTextField tipoPlazaINPUT;
    private java.awt.Label txtAparcamiento;
    private java.awt.Label txtAparcamiento1;
    private java.awt.Label txtCodigoPlaza;
    // End of variables declaration//GEN-END:variables
}
